# Generated by Django 3.1.6 on 2021-02-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='i', max_length=1)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='nutrients.nutrient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='products.product')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productnutrient',
            constraint=models.UniqueConstraint(fields=('product', 'nutrient'), name='product_nutrient'),
        ),
    ]
